name: "Remix deployment"

on:
  push:
    branches:
      - dev
      - uat
    tags:
      - "*"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: |-
      ${{
          github.ref_type == 'tag' && 'PROD'
      ||  github.ref_name == 'uat' && 'UAT'
      ||                              'DEV'
      }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.WEB_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.WEB_AWS_SECRET_ACCESS_KEY }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      DOCKER_TAG: ${{ vars.DOCKER_TAG }}
      CDK_ENVIRONMENT: ${{ vars.CDK_ENVIRONMENT }}
      EKS_CLUSTER: ${{ vars.EKS_CLUSTER }}
      EKS_ROLE_ARN: ${{ vars.EKS_ROLE_ARN }}
      EKS_ENVIRONMENT: ${{ vars.EKS_ENVIRONMENT }}
      EKS_NAMESPACE: ${{ vars.EKS_NAMESPACE }}
      DISCORD_WEBHOOK_URL: ${{ vars.DISCORD_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
            node-version: 18
      
      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          directory: deployment/overlays/${{ env.EKS_ENVIRONMENT }}
          envkey_EASYDAIRY_PRIVATE_TOKEN: ${{ secrets.EASYDAIRY_PRIVATE_TOKEN }}
          envkey_TOKEN_GENERATE_KEY: ${{ secrets.TOKEN_GENERATE_KEY }}
          envkey_BASE_URL: ${{ vars.BASE_URL }}
          envkey_E2E_BASE_URL: "http://localhost:3000"
          envkey_E2E_ADMIN_USERNAME: ${{ vars.E2E_ADMIN_USERNAME }}
          envkey_E2E_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
          envkey_E2E_BUSINESS_PREFIX: ${{ vars.E2E_BUSINESS_PREFIX }}
          envkey_E2E_USER_PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
          envkey_E2E_USER_EASYDAIRYID: ${{ vars.E2E_USER_EASYDAIRYID }}
          envkey_E2E_USER_HERDID: ${{ vars.E2E_USER_HERDID }}
          envkey_E2E_USER_CUSTOMGROUPS: ${{ vars.E2E_USER_CUSTOMGROUPS }}
          envkey_E2E_DB_HOST: ${{ vars.E2E_DB_HOST }}
          envkey_E2E_DB_PASSWORD: ${{ secrets.E2E_DB_PASSWORD }}
          envkey_E2E_DB_USER: "postgres"
          envkey_E2E_DB_NAME: "postgres"
          envkey_E2E_DB_PORT: 5432
          envkey_GA_TRACKING_ID: ${{ vars.GA_TRACKING_ID }}
          
      - name: Persist DEV .env file for local development
        if: ${{ github.ref_name == 'dev' }}
        uses: actions/upload-artifact@v4
        with:
          name: dev-env-artifact
          include-hidden-files: true
          path: deployment/overlays/${{ env.EKS_ENVIRONMENT }}/.env
      
      # - name: Cleanup E2E test data from DB (uat)
      #   uses: webiny/action-post-run@3.1.0
      #   if: ${{ github.ref_name == 'uat' }}
      #   with:
      #     run: npm run dbCleanup:deleteUsers

      # - name: Build and prepare for E2E (uat)
      #   if: ${{ github.ref_name == 'uat' }}
      #   run: |
      #     sudo cp deployment/overlays/${{ env.EKS_ENVIRONMENT }}/.env .env
      #     npm ci
      #     npm run build
      
      # - name: Run E2E tests (uat)
      #   if: ${{ github.ref_name == 'uat' }}
      #   uses: cypress-io/github-action@v6
      #   with:
      #     command: npm run test
      
      # - name: Remove .env after E2E tests pass (uat)
      #   if: ${{ github.ref_name == 'uat' }}
      #   run: |
      #     sudo rm .env

      - name: ECR login
        run: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $DOCKER_REGISTRY

      - name: Build and push image (non-prod)
        if: ${{ github.ref_type == 'branch' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

      - name: Build and push image (prod for hotfixes)
        if: ${{ github.ref_type == 'tag' && contains(github.ref_name, '-hotfix') }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
      
      - name: Retag uat image as prod (prod for non hotfix)
        if: ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-hotfix') }}
        uses: abronin/ecr-retag-action@v1
        with:
          repository: web
          aws-region: ap-southeast-2
          tag: uat
          new-tags: ${{ github.ref_name }}

      - name: Configure AWS credentials for CDK
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-skip-session-tagging: true
          aws-region: ap-southeast-2
      
      - name: Diff CDK changes
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          cdk_args: --context environment=${{ env.CDK_ENVIRONMENT }}
          working_dir: 'cdk'
      
      - name: Deploy CDK changes
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: --context environment=${{ env.CDK_ENVIRONMENT }}
          working_dir: 'cdk'

      - name: Assume EKS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.EKS_ROLE_ARN }}
          role-skip-session-tagging: true
          aws-region: ap-southeast-2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-southeast-2 --name $EKS_CLUSTER
      
      - name: Update image tag on Kustomize (prod)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          (cd deployment/overlays/$EKS_ENVIRONMENT && kustomize edit set image ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }})

      - name: Kubectl apply changes
        run: |
          kubectl apply -k deployment/overlays/$EKS_ENVIRONMENT

      - name: Kubectl rollout restart for generic image tags (non-prod)
        if: ${{ github.ref_type == 'branch' }}
        run: |
          kubectl rollout restart deployment/web -n $EKS_NAMESPACE
          kubectl rollout status deployment/web --timeout 10m -n $EKS_NAMESPACE
      
      - name: Notify Discord Channel (non-prod)
        if: ${{ github.ref_type == 'branch' }}
        run: >
          curl -H "Content-Type: application/json" -X POST 
          -d "{\"content\": \"Successfully deployed 'EasyDairy Web' from '${{ github.ref_name }}' branch to the '${{ env.EKS_ENVIRONMENT }}' environment.\"}"
          ${{ env.DISCORD_WEBHOOK_URL }}
      
      - name: Notify Discord Channel (prod)
        if: ${{ github.ref_type == 'tag' }}
        run: >
          curl -H "Content-Type: application/json" -X POST 
          -d "{\"content\": \"Successfully deployed 'EasyDairy Web' from tag '${{ github.ref_name }}' to the '${{ env.EKS_ENVIRONMENT }}' environment.\"}"
          ${{ env.DISCORD_WEBHOOK_URL }}
